def configure(ctx):
    ctx.load('sass')
    ctx.load('uglify')


def build(ctx):
    ctx.sass(source='scss/main.scss', includes=['node_modules/foundation-sites/scss/',
                                    'node_modules/motion-ui/src/',
                                    'node_modules/foundation-datepicker/css/',
                                    'node_modules/font-awesome/scss/'])

    ctx.uglify(source=['js/main.js'], target='js/app.pack.js')

    ctx.uglify(source=['node_modules/foundation-sites/js/foundation.core.js',
                       'node_modules/foundation-sites/js/foundation.abide.js',
                       'node_modules/foundation-sites/js/foundation.accordion.js',
                       'node_modules/foundation-sites/js/foundation.accordionMenu.js',
                       'node_modules/foundation-sites/js/foundation.drilldown.js',
                       'node_modules/foundation-sites/js/foundation.dropdown.js',
                       'node_modules/foundation-sites/js/foundation.dropdownMenu.js',
                       'node_modules/foundation-sites/js/foundation.equalizer.js',
                       'node_modules/foundation-sites/js/foundation.interchange.js',
                       'node_modules/foundation-sites/js/foundation.magellan.js',
                       'node_modules/foundation-sites/js/foundation.offcanvas.js',
                       'node_modules/foundation-sites/js/foundation.orbit.js',
                       'node_modules/foundation-sites/js/foundation.responsiveMenu.js',
                       'node_modules/foundation-sites/js/foundation.responsiveToggle.js',
                       'node_modules/foundation-sites/js/foundation.reveal.js',
                       'node_modules/foundation-sites/js/foundation.slider.js',
                       'node_modules/foundation-sites/js/foundation.sticky.js',
                       'node_modules/foundation-sites/js/foundation.tabs.js',
                       'node_modules/foundation-sites/js/foundation.toggler.js',
                       'node_modules/foundation-sites/js/foundation.tooltip.js',
                       'node_modules/foundation-sites/js/foundation.util.box.js',
                       'node_modules/foundation-sites/js/foundation.util.keyboard.js',
                       'node_modules/foundation-sites/js/foundation.util.mediaQuery.js',
                       'node_modules/foundation-sites/js/foundation.util.motion.js',
                       'node_modules/foundation-sites/js/foundation.util.nest.js',
                       'node_modules/foundation-sites/js/foundation.util.timerAndImageLoader.js',
                       'node_modules/foundation-sites/js/foundation.util.touch.js',
                       'node_modules/foundation-sites/js/foundation.util.triggers.js',
                       'node_modules/foundation-datepicker/js/foundation-datepicker.js',
                       'node_modules/foundation-datepicker/js/locales/foundation-datepicker.fr.js'],
               target='js/foundation.pack.js')

    ctx.uglify(source=['node_modules/angular/angular.js',
                       'node_modules/fastclick/lib/fastclick.js',
                       'node_modules/angular-ui-router/release/angular-ui-router.js'],
               target='js/angular.pack.js')


    ctx.install_files('${STATIC_PATH}/css', 'scss/main.css')
    ctx.install_files('${STATIC_PATH}/js', 'node_modules/jquery/dist/jquery.min.js')
    ctx.install_files('${STATIC_PATH}/js', 'node_modules/jquery/dist/jquery.min.map')
    ctx.install_files('${STATIC_PATH}/js', 'js/app.pack.js')
    ctx.install_files('${STATIC_PATH}/js', 'js/foundation.pack.js')
    ctx.install_files('${STATIC_PATH}/js', 'js/angular.pack.js')
    ctx.install_files('${STATIC_PATH}/.', ctx.path.ant_glob('*.html'))
    ctx.install_files('${STATIC_PATH}/px', ctx.path.ant_glob('px/*.jpg'))
    ctx.install_files('${STATIC_PATH}/templates/', ctx.path.ant_glob('templates/*.html'))
    ctx.install_files('${STATIC_PATH}/fonts', ctx.path.ant_glob('fonts/Alfphabet-IV.*'))
    ctx.install_files('${STATIC_PATH}/fonts', ctx.path.ant_glob('fonts/OpenSans*'))
    ctx.install_files('${STATIC_PATH}/fonts', ctx.path.ant_glob('node_modules/font-awesome/fonts/fontawesome-webfont.*'))
