-- Your SQL goes here
CREATE TABLE account (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	name VARCHAR NOT NULL
);

CREATE TABLE _user (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	account_id UUID NOT NULL REFERENCES account ON DELETE CASCADE,
	name VARCHAR NOT NULL
);

CREATE TABLE repayment (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	account_id UUID NOT NULL REFERENCES account ON DELETE CASCADE,
	date DATE NOT NULL,
	amount INTEGER NOT NULL,
	payer_id UUID NOT NULL REFERENCES _user ON DELETE CASCADE,
	beneficiary_id UUID NOT NULL REFERENCES _user ON DELETE CASCADE
);

CREATE TABLE expenditure (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	account_id UUID NOT NULL REFERENCES account ON DELETE CASCADE,
	name VARCHAR NOT NULL,
	date DATE NOT NULL,
	amount INTEGER NOT NULL,
	payer_id UUID NOT NULL REFERENCES _user ON DELETE CASCADE
);

CREATE TABLE debt (
	id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
	debtor_id UUID NOT NULL REFERENCES _user ON DELETE CASCADE,
	expenditure_id UUID NOT NULL REFERENCES expenditure ON DELETE CASCADE,
	share INTEGER NOT NULL
);
